using Nancy;
using NantCom.NancyBlack.Modules.DatabaseSystem;
using NantCom.NancyBlack.Modules.DatabaseSystem.Types;
using NantCom.NancyBlack.Modules.MembershipSystem;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NantCom.NancyBlack.Modules.AffiliateSystem.types
{
    /// <summary>
    /// Tracks share link click - which is not included in main pageview data
    /// this should be more valuable click that inspire buying decision
    /// </summary>
    public class AffiliateShareClick : IStaticType
    {
        #region Static Type Properties

        public int Id { get; set; }

        public DateTime __createdAt { get; set; }

        public DateTime __updatedAt { get; set; }

        #endregion

        /// <summary>
        /// Id of the affiliate
        /// </summary>
        public int AffiliateRegistrationId { get; set; }

        /// <summary>
        /// Url that was clicked - can by any arbitary url
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// IP Address that click the link
        /// </summary>
        public string IPAddress { get; set; }

        /// <summary>
        /// User GUID - as generated by NancyBlack System
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Creates the click tracking from current context
        /// </summary>
        public static void CreateFromContext( NancyContext ctx, NancyBlackDatabase db, AffiliateRegistration reg)
        {
            var owner = db.GetById<NcbUser>(reg.NcbUserId);
            var record = new AffiliateShareClick();

            record.UserId = ctx.Items["userid"] as string;

            // wont track own click
            if (record.UserId == owner.Guid.ToString())
            {
                return;
            }

            record.IPAddress = ctx.Request.UserHostAddress;
            record.Url = ctx.Request.Url.Path + "?" + ctx.Request.Url.Query;
            record.AffiliateRegistrationId = reg.Id;

            db.UpsertRecord(record);
        }
    }
}